### GET auth
GET http://localhost:4000/auth

### POST auth
POST http://localhost:4000/auth


### GET presence
GET http://localhost:4000/presence
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoxLCJmaXJzdE5hbWUiOiJmZWRpMiIsImxhc3ROYW1lIjoiYWRlbCIsImVtYWlsIjoiZmVkaTJAZ21haWwuY29tIiwicGFzc3dvcmQiOiIkMmIkMTIkcnlSNzJOamcxNUdZRHdkaWQ0L3lXZWRMY0xwRUROVWNLWXVqdG5hM2ZReVNIOHRSWTBKTkcifSwiaWF0IjoxNzE0MDc3Mzc4LCJleHAiOjE3MTQwODA5Nzh9.rU-uiHwYzLXXvtxmUAus-WcGJzSWEzx2MivWG7AM5F8


### REGISTER
POST http://localhost:4000/auth/register
Content-Type:  application/json

{
    "firstName": "fedi3",
    "lastName": "adel",
    "email" : "fedi3@gmail.com",
    "password" : "password"
}

### LOGIN
POST http://localhost:4000/auth/login
Content-Type:  application/json

{
    "email" : "fedi2@gmail.com",
    "password" : "password"
}